{"uuid": "2ebd7026-f774-4af8-a1ce-9518918e88df", "counter": 124, "stdout": "\u001b[0;31mfatal: [192.168.38.8]: FAILED! => {\u001b[0m\r\n\u001b[0;31m    \"changed\": true,\u001b[0m\r\n\u001b[0;31m    \"cmd\": [\u001b[0m\r\n\u001b[0;31m        \"python3\",\u001b[0m\r\n\u001b[0;31m        \"southbound/subnetting.py\",\u001b[0m\r\n\u001b[0;31m        \"192.168.100.0/24\"\u001b[0m\r\n\u001b[0;31m    ],\u001b[0m\r\n\u001b[0;31m    \"delta\": \"0:00:00.034419\",\u001b[0m\r\n\u001b[0;31m    \"end\": \"2024-04-21 09:23:47.415560\",\u001b[0m\r\n\u001b[0;31m    \"invocation\": {\u001b[0m\r\n\u001b[0;31m        \"module_args\": {\u001b[0m\r\n\u001b[0;31m            \"_raw_params\": \"python3 southbound/subnetting.py 192.168.100.0/24\",\u001b[0m\r\n\u001b[0;31m            \"_uses_shell\": false,\u001b[0m\r\n\u001b[0;31m            \"argv\": null,\u001b[0m\r\n\u001b[0;31m            \"chdir\": null,\u001b[0m\r\n\u001b[0;31m            \"creates\": null,\u001b[0m\r\n\u001b[0;31m            \"executable\": null,\u001b[0m\r\n\u001b[0;31m            \"removes\": null,\u001b[0m\r\n\u001b[0;31m            \"stdin\": null,\u001b[0m\r\n\u001b[0;31m            \"stdin_add_newline\": true,\u001b[0m\r\n\u001b[0;31m            \"strip_empty_ends\": true\u001b[0m\r\n\u001b[0;31m        }\u001b[0m\r\n\u001b[0;31m    },\u001b[0m\r\n\u001b[0;31m    \"msg\": \"non-zero return code\",\u001b[0m\r\n\u001b[0;31m    \"rc\": 2,\u001b[0m\r\n\u001b[0;31m    \"start\": \"2024-04-21 09:23:47.381141\",\u001b[0m\r\n\u001b[0;31m    \"stderr\": \"python3: can't open file '/home/vmadm/southbound/subnetting.py': [Errno 2] No such file or directory\",\u001b[0m\r\n\u001b[0;31m    \"stderr_lines\": [\u001b[0m\r\n\u001b[0;31m        \"python3: can't open file '/home/vmadm/southbound/subnetting.py': [Errno 2] No such file or directory\"\u001b[0m\r\n\u001b[0;31m    ],\u001b[0m\r\n\u001b[0;31m    \"stdout\": \"\",\u001b[0m\r\n\u001b[0;31m    \"stdout_lines\": []\u001b[0m\r\n\u001b[0;31m}\u001b[0m", "start_line": 113, "end_line": 146, "runner_ident": "17abe15b-a9b8-4836-a0e0-7a62e99982c5", "event": "runner_on_failed", "pid": 3499484, "created": "2024-04-21T09:23:47.541699", "parent_uuid": "52540038-3809-4fdf-6adc-000000000005", "event_data": {"playbook": "/home/vmadm/demo/RapidServe/southbound/deploy_vpc.yaml", "playbook_uuid": "d3d4f58e-717e-4bf1-8669-e9cfb6ff281e", "play": "Deploy VPC Infrastructure with network namespace", "play_uuid": "52540038-3809-4fdf-6adc-000000000002", "play_pattern": "hostvms", "task": "Get /30 subnet for current VPC", "task_uuid": "52540038-3809-4fdf-6adc-000000000005", "task_action": "command", "resolved_action": "ansible.builtin.command", "task_args": "", "task_path": "/home/vmadm/demo/RapidServe/southbound/deploy_vpc.yaml:11", "host": "192.168.38.8", "remote_addr": "192.168.38.8", "res": {"changed": true, "stdout": "", "stderr": "python3: can't open file '/home/vmadm/southbound/subnetting.py': [Errno 2] No such file or directory", "rc": 2, "cmd": ["python3", "southbound/subnetting.py", "192.168.100.0/24"], "start": "2024-04-21 09:23:47.381141", "end": "2024-04-21 09:23:47.415560", "delta": "0:00:00.034419", "msg": "non-zero return code", "invocation": {"module_args": {"_raw_params": "python3 southbound/subnetting.py 192.168.100.0/24", "_uses_shell": false, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}, "stdout_lines": [], "stderr_lines": ["python3: can't open file '/home/vmadm/southbound/subnetting.py': [Errno 2] No such file or directory"], "_ansible_no_log": null}, "start": "2024-04-21T09:23:46.946702", "end": "2024-04-21T09:23:47.541356", "duration": 0.594654, "ignore_errors": null, "event_loop": null, "uuid": "2ebd7026-f774-4af8-a1ce-9518918e88df"}}