{"uuid": "ea9408fb-65c0-4377-9037-672c85c8fa80", "counter": 124, "stdout": "\u001b[0;31mfatal: [192.168.38.8]: FAILED! => {\u001b[0m\r\n\u001b[0;31m    \"changed\": true,\u001b[0m\r\n\u001b[0;31m    \"cmd\": [\u001b[0m\r\n\u001b[0;31m        \"python3\",\u001b[0m\r\n\u001b[0;31m        \"./subnetting.py\",\u001b[0m\r\n\u001b[0;31m        \"192.168.100.0/24\"\u001b[0m\r\n\u001b[0;31m    ],\u001b[0m\r\n\u001b[0;31m    \"delta\": \"0:00:00.035117\",\u001b[0m\r\n\u001b[0;31m    \"end\": \"2024-04-21 09:21:53.218694\",\u001b[0m\r\n\u001b[0;31m    \"invocation\": {\u001b[0m\r\n\u001b[0;31m        \"module_args\": {\u001b[0m\r\n\u001b[0;31m            \"_raw_params\": \"python3 ./subnetting.py 192.168.100.0/24\",\u001b[0m\r\n\u001b[0;31m            \"_uses_shell\": false,\u001b[0m\r\n\u001b[0;31m            \"argv\": null,\u001b[0m\r\n\u001b[0;31m            \"chdir\": null,\u001b[0m\r\n\u001b[0;31m            \"creates\": null,\u001b[0m\r\n\u001b[0;31m            \"executable\": null,\u001b[0m\r\n\u001b[0;31m            \"removes\": null,\u001b[0m\r\n\u001b[0;31m            \"stdin\": null,\u001b[0m\r\n\u001b[0;31m            \"stdin_add_newline\": true,\u001b[0m\r\n\u001b[0;31m            \"strip_empty_ends\": true\u001b[0m\r\n\u001b[0;31m        }\u001b[0m\r\n\u001b[0;31m    },\u001b[0m\r\n\u001b[0;31m    \"msg\": \"non-zero return code\",\u001b[0m\r\n\u001b[0;31m    \"rc\": 2,\u001b[0m\r\n\u001b[0;31m    \"start\": \"2024-04-21 09:21:53.183577\",\u001b[0m\r\n\u001b[0;31m    \"stderr\": \"python3: can't open file '/home/vmadm/./subnetting.py': [Errno 2] No such file or directory\",\u001b[0m\r\n\u001b[0;31m    \"stderr_lines\": [\u001b[0m\r\n\u001b[0;31m        \"python3: can't open file '/home/vmadm/./subnetting.py': [Errno 2] No such file or directory\"\u001b[0m\r\n\u001b[0;31m    ],\u001b[0m\r\n\u001b[0;31m    \"stdout\": \"\",\u001b[0m\r\n\u001b[0;31m    \"stdout_lines\": []\u001b[0m\r\n\u001b[0;31m}\u001b[0m", "start_line": 113, "end_line": 146, "runner_ident": "6d9d6745-b8d8-4bec-8817-9acf294082fc", "event": "runner_on_failed", "pid": 3499199, "created": "2024-04-21T09:21:53.351402", "parent_uuid": "52540038-3809-292c-0b88-000000000005", "event_data": {"playbook": "/home/vmadm/demo/RapidServe/southbound/deploy_vpc.yaml", "playbook_uuid": "d069bfda-8cba-4dfd-bfad-5929cbdc9f7a", "play": "Deploy VPC Infrastructure with network namespace", "play_uuid": "52540038-3809-292c-0b88-000000000002", "play_pattern": "hostvms", "task": "Get /30 subnet for current VPC", "task_uuid": "52540038-3809-292c-0b88-000000000005", "task_action": "command", "resolved_action": "ansible.builtin.command", "task_args": "", "task_path": "/home/vmadm/demo/RapidServe/southbound/deploy_vpc.yaml:11", "host": "192.168.38.8", "remote_addr": "192.168.38.8", "res": {"changed": true, "stdout": "", "stderr": "python3: can't open file '/home/vmadm/./subnetting.py': [Errno 2] No such file or directory", "rc": 2, "cmd": ["python3", "./subnetting.py", "192.168.100.0/24"], "start": "2024-04-21 09:21:53.183577", "end": "2024-04-21 09:21:53.218694", "delta": "0:00:00.035117", "msg": "non-zero return code", "invocation": {"module_args": {"_raw_params": "python3 ./subnetting.py 192.168.100.0/24", "_uses_shell": false, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}, "stdout_lines": [], "stderr_lines": ["python3: can't open file '/home/vmadm/./subnetting.py': [Errno 2] No such file or directory"], "_ansible_no_log": null}, "start": "2024-04-21T09:21:52.648946", "end": "2024-04-21T09:21:53.350996", "duration": 0.70205, "ignore_errors": null, "event_loop": null, "uuid": "ea9408fb-65c0-4377-9037-672c85c8fa80"}}