{"uuid": "a944f4d9-d207-4a0b-ad38-de6c77680748", "counter": 18, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible_collections.community.docker.plugins.module_utils._api.errors.APIError: 500 Server Error for http+docker://localhost/v1.43/build?t=ta_in_container1%3Alatest&q=False&nocache=True&rm=True&forcerm=True&pull=False&dockerfile=Dockerfile-edge&buildargs=%7B%22NGINX_CONF%22%3A+%22nginx-ta_in_container1.conf%22%7D: Internal Server Error (\"Cannot locate specified Dockerfile: Dockerfile-edge\")\u001b[0m\r\n\u001b[0;31mfatal: [192.168.38.8]: FAILED! => {\"changed\": false, \"msg\": \"An unexpected Docker error occurred: 500 Server Error for http+docker://localhost/v1.43/build?t=ta_in_container1%3Alatest&q=False&nocache=True&rm=True&forcerm=True&pull=False&dockerfile=Dockerfile-edge&buildargs=%7B%22NGINX_CONF%22%3A+%22nginx-ta_in_container1.conf%22%7D: Internal Server Error (\\\"Cannot locate specified Dockerfile: Dockerfile-edge\\\")\"}\u001b[0m", "start_line": 17, "end_line": 19, "runner_ident": "36e86fd3-dc7b-42a3-925c-740b1b66fc65", "event": "runner_on_failed", "pid": 3839862, "created": "2024-04-22T02:58:22.863178", "parent_uuid": "52540038-3809-8124-cc2b-000000000008", "event_data": {"playbook": "/home/vmadm/demo/RapidServe/southbound/deploy_con.yaml", "playbook_uuid": "7af4f9bf-a22d-4904-9041-9b1fe814f778", "play": "Deploy Infrastructure with Docker Containers for Edge and Origin Servers", "play_uuid": "52540038-3809-8124-cc2b-000000000002", "play_pattern": "hostvms", "task": "Build Docker image with custom NGINX config", "task_uuid": "52540038-3809-8124-cc2b-000000000008", "task_action": "community.docker.docker_image", "resolved_action": "community.docker.docker_image", "task_args": "", "task_path": "/home/vmadm/demo/RapidServe/southbound/deploy_con.yaml:45", "host": "192.168.38.8", "remote_addr": "192.168.38.8", "res": {"exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_community.docker.docker_image_payload_0qhgv42b/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/api/client.py\", line 263, in _raise_for_status\n    response.raise_for_status()\n  File \"/usr/lib/python3/dist-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.43/build?t=ta_in_container1%3Alatest&q=False&nocache=True&rm=True&forcerm=True&pull=False&dockerfile=Dockerfile-edge&buildargs=%7B%22NGINX_CONF%22%3A+%22nginx-ta_in_container1.conf%22%7D\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/tmp/ansible_community.docker.docker_image_payload_0qhgv42b/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py\", line 1022, in main\n  File \"/tmp/ansible_community.docker.docker_image_payload_0qhgv42b/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py\", line 442, in __init__\n  File \"/tmp/ansible_community.docker.docker_image_payload_0qhgv42b/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py\", line 476, in present\n  File \"/tmp/ansible_community.docker.docker_image_payload_0qhgv42b/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py\", line 846, in build_image\n  File \"/tmp/ansible_community.docker.docker_image_payload_0qhgv42b/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/api/client.py\", line 345, in _stream_helper\n    yield self._result(response, json=decode)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/tmp/ansible_community.docker.docker_image_payload_0qhgv42b/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/api/client.py\", line 270, in _result\n    self._raise_for_status(response)\n  File \"/tmp/ansible_community.docker.docker_image_payload_0qhgv42b/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/api/client.py\", line 265, in _raise_for_status\n    raise_from(create_api_error_from_http_exception(e), e)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/tmp/ansible_community.docker.docker_image_payload_0qhgv42b/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/errors.py\", line 45, in create_api_error_from_http_exception\n    raise_from(cls(e, response=response, explanation=explanation), e)\n  File \"<string>\", line 3, in raise_from\nansible_collections.community.docker.plugins.module_utils._api.errors.APIError: 500 Server Error for http+docker://localhost/v1.43/build?t=ta_in_container1%3Alatest&q=False&nocache=True&rm=True&forcerm=True&pull=False&dockerfile=Dockerfile-edge&buildargs=%7B%22NGINX_CONF%22%3A+%22nginx-ta_in_container1.conf%22%7D: Internal Server Error (\"Cannot locate specified Dockerfile: Dockerfile-edge\")\n", "msg": "An unexpected Docker error occurred: 500 Server Error for http+docker://localhost/v1.43/build?t=ta_in_container1%3Alatest&q=False&nocache=True&rm=True&forcerm=True&pull=False&dockerfile=Dockerfile-edge&buildargs=%7B%22NGINX_CONF%22%3A+%22nginx-ta_in_container1.conf%22%7D: Internal Server Error (\"Cannot locate specified Dockerfile: Dockerfile-edge\")", "invocation": {"module_args": {"name": "ta_in_container1", "tag": "latest", "build": {"path": "/home/vmadm/demo/RapidServe/southbound", "dockerfile": "Dockerfile-edge", "args": {"NGINX_CONF": "nginx-ta_in_container1.conf"}, "nocache": true, "rm": true, "pull": false, "cache_from": null, "container_limits": null, "http_timeout": null, "network": null, "use_config_proxy": null, "target": null, "etc_hosts": null, "platform": null}, "state": "present", "source": "build", "docker_host": "unix://var/run/docker.sock", "api_version": "auto", "timeout": 60, "tls": false, "use_ssh_client": false, "validate_certs": false, "debug": false, "force_source": false, "force_absent": false, "force_tag": false, "push": false, "tls_hostname": null, "ca_cert": null, "client_cert": null, "client_key": null, "ssl_version": null, "archive_path": null, "load_path": null, "pull": null, "repository": null}}, "_ansible_no_log": null, "changed": false}, "start": "2024-04-22T02:58:21.892178", "end": "2024-04-22T02:58:22.862729", "duration": 0.970551, "ignore_errors": null, "event_loop": null, "uuid": "a944f4d9-d207-4a0b-ad38-de6c77680748"}}