{"uuid": "210814f0-00f3-4d8f-a79d-567ab1506caf", "counter": 14, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'origin_vm_ip' is undefined. 'origin_vm_ip' is undefined\u001b[0m\r\n\u001b[0;31mfatal: [localhost]: FAILED! => {\"changed\": false, \"msg\": \"AnsibleUndefinedVariable: 'origin_vm_ip' is undefined. 'origin_vm_ip' is undefined\"}\u001b[0m", "start_line": 13, "end_line": 15, "runner_ident": "81bba1be-9282-4842-a16b-174d90c09295", "event": "runner_on_failed", "pid": 3243494, "created": "2024-04-19T23:08:28.712585", "parent_uuid": "52540038-3809-a029-4e6b-000000000005", "event_data": {"playbook": "deploy_con.yaml", "playbook_uuid": "06c78e19-59f5-498b-b709-de11cf65fcb7", "play": "Deploy Infrastructure with Docker Containers for Edge and Origin Servers", "play_uuid": "52540038-3809-a029-4e6b-000000000001", "play_pattern": "localhost", "task": "Create NGINX configuration file from template for edge servers", "task_uuid": "52540038-3809-a029-4e6b-000000000005", "task_action": "template", "resolved_action": "ansible.builtin.template", "task_args": "", "task_path": "/home/vmadm/demo/RapidServe/southbound/deploy_con.yaml:26", "host": "localhost", "remote_addr": "127.0.0.1", "res": {"msg": "AnsibleUndefinedVariable: 'origin_vm_ip' is undefined. 'origin_vm_ip' is undefined", "exception": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/ansible/template/__init__.py\", line 987, in do_template\n    res = self.environment.concat(rf)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/ansible/template/native_helpers.py\", line 88, in ansible_concat\n    return ''.join([to_text(v) for v in nodes])\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/ansible/template/native_helpers.py\", line 88, in <listcomp>\n    return ''.join([to_text(v) for v in nodes])\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<template>\", line 13, in root\n  File \"/usr/lib/python3/dist-packages/ansible/template/__init__.py\", line 262, in wrapper\n    ret = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/ansible/template/__init__.py\", line 511, in _ansible_finalize\n    return thing if _fail_on_undefined(thing) is not None else ''\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/ansible/template/__init__.py\", line 483, in _fail_on_undefined\n    elif is_sequence(data):\n         ^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/ansible/module_utils/common/collections.py\", line 94, in is_sequence\n    if not include_strings and is_string(seq):\n  File \"/usr/lib/python3/dist-packages/jinja2/runtime.py\", line 852, in _fail_with_undefined_error\n    raise self._undefined_exception(self._undefined_message)\njinja2.exceptions.UndefinedError: 'origin_vm_ip' is undefined\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/ansible/plugins/action/template.py\", line 141, in run\n    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/ansible/template/__init__.py\", line 1021, in do_template\n    raise AnsibleUndefinedVariable(e, orig_exc=e)\nansible.errors.AnsibleUndefinedVariable: 'origin_vm_ip' is undefined. 'origin_vm_ip' is undefined\n", "_ansible_no_log": null, "changed": false}, "start": "2024-04-19T23:08:28.620508", "end": "2024-04-19T23:08:28.712112", "duration": 0.091604, "ignore_errors": null, "event_loop": null, "uuid": "210814f0-00f3-4d8f-a79d-567ab1506caf"}}